In [1]:
from yahtzee import Game
from constants import CATEGORIES
from greedy_strategy import greedy_strategy
from itertools import combinations_with_replacement, combinations, product
from collections import Counter
import numpy as np
import pandas as pd
from tqdm import tqdm

# 1. Simple greedy strategy
Prioritize expected score of next most imminent roll

## a. First greedy variant: Prioritize earning upper section bonus

In [4]:
i

151

In [3]:
game_states_upper = []

# Use different seed for each iteration
for i in tqdm(range(1, 10000, 5), miniters=10000/100):
    game_states_upper.append(greedy_strategy(start_seed=i, prioritize_upper_section=True))

  0%|          | 0/2000 [00:00<?, ?it/s]

[6 5 5 4 5]
[6 4 4 6 1]
[2 5 3 4 3]
[3 1 3 3 1]
[5 4 5 5 2]
[3 1 1 2 3]
[5 3 3 6 6]
[4 4 4 4 3]
[2 6 5 3 5]
[5 5 6 3 1]
[2 3 4 5 2]
[3 2 5 3 1]
[3 4 2 6 5]
[3 6 6 4 5]
[6 5 5 5 4]
[4 2 6 5 6]
[2 6 3 6 6]
[5 5 3 1 5]
[1 5 2 3 4]
[1 3 2 3 6]
[5 2 2 1 1]
[6 4 4 6 6]
[4 4 4 5 2]
[3 6 6 2 6]
[5 5 2 5 2]
[1 2 1 6 5]
[3 6 6 5 5]
[4 2 5 6 3]
[6 3 6 4 1]
[6 5 1 5 5]
[4 6 6 5 3]
[3 4 1 3 3]
[4 3 5 4 5]
[4 6 4 4 4]
[2 2 3 4 6]
[5 2 2 2 2]
[4 5 5 4 4]
[5 6 6 6 6]
[4 1 4 6 3]
[3 4 5 6 1]
[4 3 6 2 4]
[6 3 4 5 1]
[6 1 3 2 6]
[5 1 5 3 5]
[5 5 6 4 4]
[6 4 5 4 2]
[4 1 5 3 1]
[1 2 4 3 5]
[2 4 4 4 2]
[6 6 5 6 4]
[2 2 1 5 5]
[3 3 3 3 2]
[4 2 1 3 1]
[5 4 6 4 3]
[4 6 5 4 6]
[6 6 3 6 2]
[6 4 2 5 5]
[5 3 3 3 3]
[2 2 4 1 5]
[6 2 5 5 1]
[5 5 4 4 4]
[2 3 5 1 4]
[2 1 1 2 5]
[3 3 6 3 3]
[3 6 6 2 3]
[2 1 5 4 3]
[5 6 2 4 5]
[4 2 6 1 6]
[2 2 6 1 2]
[4 3 5 5 4]
[2 2 2 6 2]
[4 2 1 4 4]
[3 3 6 6 6]
[6 5 3 6 5]
[4 2 4 3 5]
[2 4 3 2 1]
[2 6 2 5 4]
[3 1 1 4 1]
[5 4 6 6 3]
[5 2 4 3 6]
[2 5 5 5 6]
[6 6 4 6 3]
[2 6 2 6 6]
[6 5

  2%|▏         | 30/2000 [00:04<04:35,  7.16it/s]

[5 4 6 6 4]
[5 4 3 1 2]
[1 5 4 6 5]
[6 6 6 6 6]
[3 3 6 6 3]
[6 2 2 6 2]
[4 4 6 6 1]
[3 5 3 5 3]
[6 6 6 6 6]


TypeError: len() takes exactly one argument (0 given)

In [38]:
df_upper = pd.DataFrame(game_states_upper)
df_upper.drop(columns=['available_categories', 'potential_scores', 'rolls_remaining', 'dice_values'], inplace=True)

In [39]:
df_upper['num_yahtzees'].value_counts()

num_yahtzees
0    1448
1     552
Name: count, dtype: int64

In [40]:
round_scores = pd.DataFrame(df_upper['scores'].to_list(), columns = CATEGORIES)

round_scores['flag'] = np.where(
    ((round_scores['1s'] == 5) | \
    (round_scores['2s'] == 10) | \
    (round_scores['3s'] == 15) | \
    (round_scores['4s'] == 20) | \
    (round_scores['5s'] == 25) | \
    (round_scores['6s'] == 30)), 1, 0
)

In [42]:
66*5+1

331

In [41]:
round_scores.loc[round_scores['flag']==1]

1s    2s    3s    4s    5s    6s  3_of_a_kind  4_of_a_kind  full_house  \
58    2.0   4.0  15.0   8.0  15.0  12.0         13.0         13.0        25.0   
66    2.0   6.0   6.0   8.0  10.0  30.0         22.0         28.0        25.0   
121   1.0   6.0  15.0  12.0  10.0   6.0         28.0         18.0        25.0   
123   5.0   0.0   6.0   8.0  10.0   6.0         27.0          0.0        25.0   
251   0.0  10.0   3.0   4.0  15.0   6.0         29.0         13.0        25.0   
301   5.0   4.0   6.0   8.0  10.0  12.0         12.0          0.0        25.0   
476   2.0  10.0   6.0   8.0  10.0  18.0         22.0         28.0        25.0   
529   3.0   6.0   9.0  20.0  10.0   6.0         23.0         24.0        25.0   
893   1.0   4.0   6.0  12.0  25.0   6.0         26.0         25.0        25.0   
917   3.0   4.0   6.0  20.0  10.0   6.0         23.0         26.0        25.0   
924   5.0   6.0   6.0   8.0  10.0  12.0         10.0         13.0        25.0   
940   0.0   6.0  15.0   8.0  10.0  12.0          8.0         29.0        25.0   
1048  0.0   0.0  15.0  12.0  10.0  18.0          9.0         22.0        25.0   
1053  5.0   4.0   9.0   4.0  15.0   6.0         20.0         12.0        25.0   
1056  3.0   0.0   3.0   4.0  20.0  30.0         18.0         29.0        25.0   
1063  0.0   6.0   9.0   8.0  25.0  12.0         24.0         27.0        25.0   
1115  3.0   4.0   6.0  20.0  10.0  24.0         27.0         29.0        25.0   
1147  1.0   4.0   6.0  20.0  10.0  18.0         26.0         16.0        25.0   
1234  0.0   2.0   6.0   8.0  25.0  12.0         23.0         15.0        25.0   
1238  5.0   4.0   6.0  12.0  10.0  12.0         27.0         29.0        25.0   
1299  0.0   4.0   6.0   4.0  15.0  30.0         25.0         28.0        25.0   
1343  5.0   4.0   6.0  12.0  10.0   6.0         25.0         18.0        25.0   
1387  2.0   2.0  15.0  12.0  15.0   0.0         27.0         27.0        25.0   
1397  0.0  10.0  12.0  12.0  20.0  24.0         17.0         14.0        25.0   
1408  2.0   8.0  15.0   8.0  10.0  12.0         27.0         22.0        25.0   
1480  3.0   6.0  15.0  12.0  10.0  12.0         19.0         16.0        25.0   
1506  3.0   4.0  15.0   8.0  15.0  12.0         10.0         14.0        25.0   
1634  0.0   4.0   9.0   8.0  25.0  18.0         25.0         23.0        25.0   
1690  2.0   6.0   9.0  20.0   5.0  12.0         25.0         26.0        25.0   
1692  1.0   4.0  15.0  12.0   5.0  12.0         13.0         25.0        25.0   
1764  2.0   4.0   6.0  12.0  25.0  12.0         25.0         12.0        25.0   
1774  3.0   0.0   6.0   8.0  25.0   6.0         23.0         25.0        25.0   
1810  1.0  10.0   9.0   4.0   5.0  18.0         28.0          0.0        25.0   
1846  0.0   4.0   6.0  20.0  10.0  12.0         24.0         28.0        25.0   
1865  0.0  10.0   9.0   8.0  10.0  18.0         24.0         18.0        25.0   
1960  3.0   0.0   9.0   8.0  25.0  18.0         19.0         15.0        25.0   

      sm_straight  lg_straight  yahtzee  chance  flag  
58           30.0         40.0     50.0    23.0     1  
66           30.0         40.0     50.0    20.0     1  
121          30.0         40.0     50.0    19.0     1  
123          30.0         40.0     50.0    16.0     1  
251          30.0         40.0     50.0    18.0     1  
301          30.0         40.0     50.0    24.0     1  
476          30.0         40.0     50.0    25.0     1  
529          30.0         40.0     50.0    22.0     1  
893          30.0         40.0     50.0    25.0     1  
917          30.0         40.0     50.0    23.0     1  
924          30.0         40.0     50.0    22.0     1  
940          30.0         40.0     50.0    17.0     1  
1048         30.0         40.0     50.0    12.0     1  
1053         30.0         40.0     50.0    22.0     1  
1056         30.0         40.0     50.0    14.0     1  
1063         30.0         40.0     50.0    18.0     1  
1115         30.0         40.0     50.0    21.0     1  
1

## b. Second greedy variant: Do not prioritize earning upper section bonus

In [ ]:
game_states_no_upper = []

# Use different seed for each iteration
for i in tqdm(range(5000), miniters=5000/100):
    game_states_no_upper.append(greedy_strategy(start_seed=i, prioritize_upper_section=False))